services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    labels:
      glance.name: StirlingPDF
      glance.icon: di:stirling-pdf
      glance.url: https://stirlingpdf.felix0351.duckdns.org
      glance.description: PDF manipulation tool
    networks:
      - reverse-proxy
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/logs:/logs/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=de_DE

networks:
  reverse-proxy:
    external: true
